name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: |
          sudo docker build -f Dockerfile -t tiktak-service-permission-test:latest .
        shell: bash

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to Server
        run: |
          sudo bash -c 'cd /root/ && docker compose up -d tiktak-service-permission-test'
        shell: bash
